# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main

variables:
- group: terraform

pool:
  vmImage: ubuntu-latest

steps:
- script: env
  displayName: 'env'

- script: |
    export TF_VAR_user_admin_gpg_key=$(AZ_VAL_TF_VAR_user_admin_gpg_key)
    export AWS_ACCESS_KEY_ID=$(AZ_VAL_AWS_ACCESS_KEY_ID)
    export AWS_SECRET_ACCESS_KEY=$(AZ_VAL_AWS_SECRET_ACCESS_KEY)
    terraform init
  displayName: 'init'

- script: |
    export TF_VAR_user_admin_gpg_key=$(AZ_VAL_TF_VAR_user_admin_gpg_key)
    export AWS_ACCESS_KEY_ID=$(AZ_VAL_AWS_ACCESS_KEY_ID)
    export AWS_SECRET_ACCESS_KEY=$(AZ_VAL_AWS_SECRET_ACCESS_KEY)
    terraform plan
  displayName: 'plan'
